FROM node:14

RUN mkdir -p /usr/src/node-api
WORKDIR /usr/src/node-api
COPY . .

ENV NODE_ENV=production
ENV NODE_APP_CORS_URL=https://personal-portfolio.azurewebsites.net
ENV NODE_APP_API_URL=https://ire1.blob.core.windows.net/personal-portfolio

RUN npm install --production && npm run build:prod

EXPOSE 3000

CMD [ "npm", "start" ]
